version: 1.0.{build}-{branch}

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools pyinstaller tqdm"

build_script:
  - "%PYTHON%\\Scripts\\pyinstaller.exe DuplicateFolderFinder.spec"

artifacts:
  - path: dist/DuplicateFolderFinder.exe
